name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^10.1.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  retrofit: ^4.0.1
  dio: ^5.3.2
#  mocktail: ^1.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  get_it: ^7.6.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  bloc_test: ^9.1.4
  freezed: ^2.4.1
  mockito: ^5.0.15
  mocktail: ^0.2.0
  intl: ^0.18.1
  http: ^0.13.3

flutter:
  uses-material-design: true

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sfprodisplay/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/sfprodisplay/SF-Pro-Display-Medium.otf
          weight: 700
        - asset: assets/fonts/sfprodisplay/SF-Pro-Display-Light.otf
          weight: 300